WazeDev/WME-URComments-Enhanced

WME-URComments-Enhanced.js
-NEW: WazeWrap update integration.
-BUGFIX: Not able to change lists in some situations.
-BUGFIX: ZoomIn on new.
-BUGFIX: WME bug workaround.
-BUGFIX: AutoCenter on commented.
-BUGFIX: Last Comment By in popup.-
-Other slight changes to prevent future bugs.
=> Merge beta into master for 2018.02.04.02

WME-URComments-Enhanced.js
NEW: Per comment list settings!
ENHANCEMENT: Handle changing to MTE mode and back cleanly.
ENHANCEMENT: Append mode now inserts new comment at cursor position.
ENHANCEMENT: Customizable unstack sensitivity and disable above zoom (zoomed out beyond) level.
ENHANCEMENT: Unstack markers now temporarily hides markers not involved in the unstacking.
ENHANCEMENT: Split Auto set new UR comment (with description) out to not insert on SLURs and added a new setting of Auto set new UR Comment (SLUR).
ENHANCEMENT: Better overflow handling. Now queues sub-quadrants to get ALL URs.
ENHANCEMENT: Improved center on UR (popup link), UR Panel crosshairs click and center on UR function.
ENHANCEMENT: Added dismiss button for over limit message and need translation message.
ENHANCEMENT: Removed unnecessary …
=> Merge beta with master for 2019.03.06.01

WME-URComments-Enhanced.js
<b>BUGFIX:</b> 2019.04.12.01 had issue with new fully casual shortcut.
=> 2019.04.12.02

WME-URComments-Enhanced.js
<b>CHANGE:</b> Using WazeWrap alert system.
<b>BUGFIX:</b> Restrictions not updating correctly on map move in certain situations.
<b>BUGFIX:</b> Need translation message box not displayed correctly.
<b>BUGFIX:</b> Last comment more than days old filter.
=> Merge beta with master for 2019.05.04.01

WME-URComments-Enhanced.js
2019.07.24.01
BUGFIX: Further refinement of unstacking and selection.
CHANGE: Future deprecation of properties for countries and states.
=> Merge beta to master for 2019.07.24.01.

WME-URComments-Enhanced.js
2019.08.16.01:
<b>NEW:</b> Custom text replace variables via sheets.
<b>NEW:</b> Custom tagline setting. (Per comment list or "master")
<b>NEW:</b> More shortcuts: current date, current date casual, current day of week, current time, current time casual, custom tagline, place address, place name, UR type. (Available via UR panel and variable in comments)
<b>NEW:</b> $SELSEGS_WITH_CITY$ : Same as $SELSEGS$, except includes \'in CITY\' if selected segment(s) have a matching primary city, or only one has a primary city.
<b>NEW:</b> Link to enable / disable URCE UR filtering added to comment tab.
<b>BUGFIX:</b> Per comment list text boxes not saving correctly.
<b>BUGFIX:</b> Check for ALL $$ in comment before automatically clicking send.
<b>BUGFIX:</b> Selected segments variable replacement …
=> Merge Beta into master for 2019.08.16.01

WME-URComments-Enhanced.js
<b>CHANGE:</b> Changed restrictions applied to be a warning icon in settings and comment list.
<b>BUGFIX:</b> Another fix for the restrictions alert.
=> Merge beta into master for 2019.08.30.01

WME-URComments-Enhanced.js
<b>NEW:</b> Remember collapsed state of <i>More Information</i> box in UR Panel.
<b>NEW:</b> Unknown venue name (no name on venue / place) is now translatable to locale(s).
<b>NEW:</b> Unknown road name (no name on road / segment) is now translatable to locale(s).
<b>BUGFIX:</b> Translations not loading correctly in certain situations.
<b>BUGFIX:</b> Variable detection improvement.
<b>BUGFIX:</b> Variables slipping through auto-post reminder routine in certain situations.
=> Merge Beta into Master for 2019.09.25.01

WME-URComments-Enhanced.js
<b>CHANGE:</b> WME v2.43-40-gf367bffa4 compatibility.
=> Merge Beta with master for 2019.12.06.01

WME-URComments-Enhanced.js
<b>NEW:</b> Added a setting to exclude tagged URs from auto-send reminders
<b>CHANGE:</b> Latest WME compatibility.
<b>CHANGE:</b> Major under-the-hood work to enhance performance.
<b>BUGFIX:</b> Further refinement for latest WME compatibility.
<b>BUGFIX:</b> Error loading in non-translated language locales.
<b>BUGFIX:</b> Restrictions causing errors in certain countries.
<b>BUGFIX:</b> Shortcuts chevron upside down.
=> Merge Beta to master for 2020.06.16.01

WME-URComments-Enhanced.js
<b>CHANGE:</b> WME map object references.
<b>BUGFIX:</b> Spinner handling routines to reduce or remove stuck spinning.
<b>BUGFIX:</b> Per comment list tag email not saving correctly.
=> Merge beta to master for 2020.07.27.02

WME-URComments-Enhanced.js
<b>NEW:</b> Setting to auto zoom out after closing UR panel.
<b>NEW:</b> Shortcut to insert permalink to UR.
<b>NEW:</b> Spreadsheet shortcut of "$PERMALINK$" to insert permalink to UR.
<b>CHANGE:</b> Faster load time.
<b>CHANGE:</b> Far less script execution awaits, letting script run more synchronously.
<b>CHANGE:</b> Style compatibility with WME v2.62-35-g266443036.
<b>BUGFIX:</b> Script style setting not correctly showing in settings.
<b>BUGFIX:</b> Better error handling.
<b>BUGFIX:</b> WazeWrap stored settings not applied in some cases.
<b>BUGFIX:</b> Multiple event listeners in certain situations.
<b>BUGFIX:</b> Width of UR panel not wide enough for text (native WME issue).
=> Merge beta to master for 2020.09.08.02

WME-URComments-Enhanced.js
<b>NEW:</b> Setting to auto zoom out after closing UR panel.
<b>NEW:</b> Shortcut to insert permalink to UR.
<b>NEW:</b> Spreadsheet shortcut of "$PERMALINK$" to insert permalink to UR.
<b>CHANGE:</b> Faster load time.
<b>CHANGE:</b> Far less script execution awaits, letting script run more synchronously.
<b>CHANGE:</b> Style compatibility with WME v2.62-35-g266443036.
<b>BUGFIX:</b> Permalink shortcut icon not working correctly. (2020.09.09.01)
<b>BUGFIX:</b> Side panel alignments in certain situations. (2020.09.09.01)
<b>BUGFIX:</b> Script style setting not correctly showing in settings.
<b>BUGFIX:</b> Better error handling.
<b>BUGFIX:</b> WazeWrap stored settings not applied in some cases.
<b>BUGFIX:</b> Multiple event listeners in certain situations.
<b>BUGFIX:</b> Width of UR panel …
=> Merge beta to master for 2020.09.09.01

WME-URComments-Enhanced.js
<b>BUGFIX:</b> Fix for WME changes - missing day names.
=> 2021.07.14.01

WME-URComments-Enhanced.js
<b>CHANGE:</b> Update zoom levels to new WME values.
=> Merge beta to master 2021.08.30.01

WME-URComments-Enhanced.js
<b>NEW:</b> Setting to change comments sort order.
<b>NEW:</b> CSS updates to make UR panel more screen space efficient.
<b>NEW:</b> Setting to allow auto expanding of shortcuts section.
<b>NEW:</b> Setting to allow auto expanding of more info section.
=> Merge Beta to master for 2022.01.20.02

WME-URComments-Enhanced.js
<b>CHANGE:</b> Fix replace next with done setting after latest WME update.
<b>CHANGE:</b> CSS to allow buttons to expand.
<b>CHANGE:</b> Changes to formatting  per new ESLINT options.
<b>CHANGE:</b> Days ago on incorrect comments due to comment order reverted to oldest first in latest WME update.
=> Merge beta to master for 2022.03.02.01

WME-URComments-Enhanced.js
<b>CHANGE:</b> Fix replace next with done setting after latest WME update.
<b>CHANGE:</b> CSS to allow buttons to expand.
<b>CHANGE:</b> Changes to formatting  per new ESLINT options.
<b>CHANGE:</b> Days ago on incorrect comments due to comment order reverted to oldest first in latest WME update.
<b>BUGFIX:</b> Scroll comments.
<b>BUGFIX:</b> UR panel failed to show when clicking on pill instead of marker.
=> Merge beta into master for 2022.03.03.01

WME-URComments-Enhanced.js
Sorry about the PR spam. I had forgotten I needed to rebase onto beta :/
=> Fixed "Close needed" filtering (for good)

WME-URComments-Enhanced.js
<b>CHANGE:</b> Sidepanel width in latest WME release.
<b>CHANGE:</b> Detection of UR panel in latest WME release.
=> Merge Beta into master for 2022.10.19.01

WME-URComments-Enhanced.js
`.conversation-region` is gone, let's not use it for selectors anymore.
Also updated checkbox selector.
=> WME v2.134 fixes

WME-URComments-Enhanced.js
<b>CHANGE:</b> Compatibility with latest WME release.
=> Merge beta to master for 2023.03.01.01

.gitattributes, WME-URComments-Enhanced.js
<b>NEW:</b> Close button for UR marker mouseover popup.
<b>NEW:</b> Link to disable UR marker mouseover popups within popup.
<b>CHANGE:</b> New bootstrap routine.
<b>CHANGE:</b> Updated code to use optional chaining.
<b>CHANGE:</b> Utilize (@)match instead of (@)include in userscript headers.
<b>CHANGE:</b> Code cleanup.
<b>CHANGE:</b> WazeWrap compatibility.
=> Merge Beta to master for 2023.03.15.01

WME-URComments-Enhanced.js
<b>NEW:</b> Move scroll bar for comments / settings to only be for that div element.
<b>CHANGE:</b> Use WME API to create userscripts tab.
<b>CHANGE:</b> Auto-send reminder comments restricted to editors ranked 4 and above (or 3 and above with AM).
<b>CHANGE:</b> Auto-send reminder will not send to URs that contain a complete set of square brackets anywhere within text.
<b>BUGFIX:</b> URC-E not catching UR correctly when a UR panel is already open.
<b>BUGFIX:</b> Auto-send reminder comments sending to URs not on screen in certain situations.
=> Merge Beta to master for 2023.03.27.01

WME-URComments-Enhanced.js
NEW: Check for updated version on load.
BUGFIX: Issues when Issue Tracker has greater than 499 URs.
BUGFIX: UR Panel showed -1 for urId in certain situations.
BUGFIX: Save button observer in WME beta.
BUGFIX: Restore settings resulted in error before completion.
CHANGE: Moved urceData to private object instead of WME model.
CHANGE: "Enable UR Overflow" no longer applies if zoom level is less than 10.
CHANGE: Auto-send reminder comment will no longer send if zoom level is less than 10.
CHANGE: Miscellaneous code variable changes.
CHANGE: Issue tracker bugfix also resulted in necessity to disable auto refresh setting.
CHANGE: Future (possible) WME changes preparation. (fixed)
=> 2023.04.05.02

WME-URComments-Enhanced.js
**CHANGE:** Steps for custom Google sheet creation updated.
**CHANGE:** WME production now includes function from WME beta.
=> 2023.04.19.01

WME-URComments-Enhanced.js
**CHANGE:** Steps for custom Google sheet creation updated.
**CHANGE:** WME production now includes function from WME beta.
**BUGFIX:** Autosave after close or not identified comment.
=> 2023.04.19.02

WME-URComments-Enhanced.js
NEW: Further prep work for possible future spreadsheet changes.
NEW: $URID$ now available as a variable to use in our comments. Will insert the UR ID number of the selected UR.
CHANGE: A lot. Reverted to 100% vanilla JavaScript, removing reliance on jQuery.
CHANGE: Switch to WazeWrap update checking.
CHANGE: WME changes to repositories.
CHANGE: Switch to Waze icons instead of FontAwesome for continuity.
CHANGE: Remove unnecessary marker event listener.
BUGFIX: Filter "hide with description".
=> 2023.05.18.01

WME-URComments-Enhanced.js
NEW: (2023.05.19.02) Place cursor at start setting.
NEW: Further prep work for possible future spreadsheet changes.
NEW: $URID$ now available as a variable to use in our comments. Will insert the UR ID number of the selected UR.
CHANGE: A lot. Reverted to 100% vanilla JavaScript, removing reliance on jQuery.
CHANGE: Switch to WazeWrap update checking.
CHANGE: WME changes to repositories.
CHANGE: Switch to Waze icons instead of FontAwesome for continuity.
CHANGE: Remove unnecessary marker event listener.
BUGFIX: Filter "hide with description".
BUGFIX: (2023.05.19.01) Incorrect minimum version # for old static comment list in version 2023.05.18.01.
=> 2023.05.19.02

WME-URComments-Enhanced.js
=> 2023.06.02.01

WME-URComments-Enhanced.js
CHANGE: WME release v2.180-7-geb388e8d3 compatibility.
=> 2023.08.02.01

WME-URComments-Enhanced.js
CHANGE: WME release v2.180-7-geb388e8d3 compatibility.
=> 2023.08.03.01

WME-URComments-Enhanced.js
CHANGE: WME beta release v2.188 compatibility.
=> 2023.09.29.01

WME-URComments-Enhanced.js
CHANGE: Remove setting unfollowUrAfterSend and all code references.
=> 2023.11.03.01

WME-URComments-Enhanced.js
CHANGE: Fix collapsing of containers after a WME update.
=> 2023.11.29.01

WME-URComments-Enhanced.js
CHANGE: Fix collapsing of containers after a WME update.
BUGFIX: Custom sheet creation steps only worked with en-US locale.
=> 2023.11.29.02

WME-URComments-Enhanced.js
CHANGE: Compatibility with latest WME update.
CHANGE: Auto set new UR comment with description restriction will ignore if description is "Reported map issue"
=> 2024.06.06.01

WME-URComments-Enhanced.js
CHANGE: Compatibility with latest WME update.
CHANGE: A UR with "Reported map issue" as the decsription is treated as if it were "without description".
=> 2024.06.06.02

WME-URComments-Enhanced.js
CHANGE: WME beta release v2.242 compatibility
=> Merge beta to master for 2024.08.20.01

WME-URComments-Enhanced.js
CHANGE: WME release vv2.261-6-gce1dd85be compatibility.
=> 2024.11.26.01

WME-URComments-Enhanced.js
CHANGE: WME release vv2.261-6-gce1dd85be compatibility.
=> Merge beta to master for 2024.11.26.02

WME-URComments-Enhanced.js
CHANGE: WME release v2.287-5-g32b915ed8 compatibility.
=> 2025.04.23.01
